import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav 
          >
         <div style={{width:"100%",display:"flex"}}>
          <Link href="/" style={{margin:"10px"}}>Home</Link>
            <Link href="/about" style={{margin:"10px"}}>About</Link>
            <Link href="/contact" style={{margin:"10px"}}>Contact</Link>
            <Link href="/users" style={{margin:"10px"}}>Users</Link>
            <Link href="/post" style={{margin:"10px"}}>Post</Link>

         </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
